### ISSUE TITLE
Integration with Redux Devtools?

### ISSUE THREAD

**Issue by alukach** [o0y0o/use-reducer-x#2]
Are there any examples of integrating Redux Devtools with this? Any reason why it shouldn't work?  I seem to be having some troubles getting it to work but admittedly that may have more to do with my lack of knowledge around the inner-workings of this library and/or Redux.

**Comment by llaenowyd** [comment]
Seems [reinspect](https://github.com/troch/reinspect) might be the best way to use Redux Dev Tools (browser extension) with `useReducer`. Something has to make it work when you can effectively have multiple "stores" with several `useReducer`s and no `redux.combineReducers`.

But then, am I missing something or the API of `reinspect.useReducer` is basically incompatible with `useEnhancedReducer`?  Neither one seems pluggable to let you supply an optional "underlying useReducer" instead of `React.useReducer`
